name: sPonGeBoBmEMe
main: dktapps\sPonGeBoBmEMe\Main
version: 1.0.2
api: [3.25.0]
load: POSTWORLD
author: dktapps
description: a pLugIn fOr pOckETMiNe-mP tO maKe aLL ChaT mEssAgeS lOoK liKe thIs
website: https://github.com/dktapps/sPonGeBoBmEMe
